"""create notes table

Revision ID: aaf0ac4f6333
Revises: a502d476fac8
Create Date: 2026-08-05 22:34:25.090447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaf0ac4f6333'
down_revision: Union[str, Sequence[str], None] = 'a502d476fac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes_new', sa.Column('pinned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes_new', 'pinned')
    # ### end Alembic commands ###
